services:
  - type: web
    name: certificados-app
    env: python
    buildCommand: pip install -r requirements.txt && python check_db.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --threads 4 --worker-class gthread --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true 